### ISSUE TITLE
Bug: image floats inside next block

### ISSUE THREAD

**Issue by MoamenAbdelsattar** [vivliostyle/vivliostyle.js#1418]
I'm trying to use page floats, so I set `float: top` for the following image. The result is image inside the following poetic verse, instead of being above it:
![v-float-bug](https://github.com/user-attachments/assets/089a67c1-6594-447a-aaf3-70de8d4fa02c)

Expected result:
![v-flot-bug2](https://github.com/user-attachments/assets/d2b84702-b4d3-47a4-9712-d835cd301854)

**Comment by MoamenAbdelsattar** [comment]
Problem can be easily fixed by adding `clear: both;` to the following div After pagination. Adding it before pagination doesn't solve the issue.

**Comment by MoamenAbdelsattar** [comment]
Hi, problem is solved after using [epub partitions](https://docs.vivliostyle.org/#/supported-css-features#epub-adaptive-layout) instead of page floats, however the documentation says "Future version of Vivliostyle may drop support for this spec." I hope that doesn't happen 😶

**Comment by MurakamiShinyu** [comment]
There was a similar issue:

- https://github.com/vivliostyle/vivliostyle.js/issues/1071

This issue was fixed by pr #1075.

However, the problem still happens if the page float width is narrower than page area width.

To avoid the problem, specify `float` on the image's parent block element (e.g., `figure` element) and align the image in it.

I hope this helps.
